/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package a;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Andres Varela
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        iniciar_crear.setVisible(true);
        PantalladeCarga.setVisible(false);
        MenuAdmin.setVisible(false);
        MenuUsuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuUsuario = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablacompra = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton8 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton10 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        contra = new javax.swing.JLabel();
        usu = new javax.swing.JLabel();
        MenuAdmin = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ConcesionariaNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ConcesionariaLocacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        modelo_c = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cb_concesionaria = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        marca_c = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        carro_color = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        precio_carro = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        velocidad_punta = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        pais_c = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        cb_tiempo = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        caballero_fuerza = new javax.swing.JTextField();
        Reconstruido = new javax.swing.JCheckBox();
        Fecha = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ClasificacionPartes = new javax.swing.JComboBox<>();
        MarcaPartes = new javax.swing.JComboBox<>();
        PrecioPartes = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        longitud = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        locacion = new javax.swing.JTextField();
        tipo_carrera = new javax.swing.JComboBox<>();
        curvas = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PantalladeCarga = new javax.swing.JPanel();
        barra2 = new javax.swing.JProgressBar();
        barra1 = new javax.swing.JProgressBar();
        iniciar_crear = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        i_usuario = new javax.swing.JTextField();
        i_contrasena = new javax.swing.JTextField();
        Listo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Contrasena = new javax.swing.JTextField();
        Pais = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        fecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablacompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Precio", "Año de fabricación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablacompra);

        jButton7.setText("Actualización");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Comprar", jPanel7);

        jList2.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jList2);

        jButton8.setText("Actualización");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Vender", jPanel8);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Instalar Partes", jPanel10);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Simulador", jPanel9);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Precio", "Año de fabricación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 540, 460));

        jList1.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jList1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 260, 350));

        jButton10.setText("Actualización");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));

        jTabbedPane4.addTab("Garaje", jPanel4);

        MenuUsuario.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 880, 530));

        jButton4.setText("<-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        MenuUsuario.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 40));

        contra.setText("jLabel32");
        MenuUsuario.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 140, 40));

        usu.setText("jLabel32");
        MenuUsuario.add(usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 140, 40));

        jTabbedPane3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane3StateChanged(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(ConcesionariaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 127, 158, -1));

        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 129, -1, -1));

        jLabel5.setText("Locación");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 166, -1, -1));
        jPanel1.add(ConcesionariaLocacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 164, 158, -1));

        jLabel6.setText("Nueva Concesionaria");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 94, 174, -1));

        jButton1.setText("crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 231, 204, 73));

        jTabbedPane3.addTab("Agregar Concesionaria", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.add(modelo_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, 32));

        jLabel18.setText("Velocidad Punta");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, 30));

        jLabel19.setText("Pais");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 30, -1));

        jPanel3.add(cb_concesionaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 150, 32));

        jLabel20.setText("Marca");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 40, 30));

        marca_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marca_cMouseClicked(evt);
            }
        });
        jPanel3.add(marca_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, 32));

        jLabel21.setText("Modelo");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 40, 10));

        carro_color.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout carro_colorLayout = new javax.swing.GroupLayout(carro_color);
        carro_color.setLayout(carro_colorLayout);
        carro_colorLayout.setHorizontalGroup(
            carro_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        carro_colorLayout.setVerticalGroup(
            carro_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(carro_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, 30));

        jLabel22.setText("Color");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 40, 30));
        jPanel3.add(precio_carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 150, 30));

        jLabel24.setText("Precio");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, 10));

        jLabel26.setText("Horsepower");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 110, 30));
        jPanel3.add(velocidad_punta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 100, 30));

        jLabel27.setText("Concesionaria");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 110, 30));

        pais_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USA", "Alemania", "Japon", "Italia" }));
        pais_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pais_cMouseClicked(evt);
            }
        });
        jPanel3.add(pais_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, 32));

        jButton5.setText("Crear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 160, 50));

        jLabel28.setText("Tiempo");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 165, 110, 40));

        cb_tiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 a 60 km/h ", "0 a 100 km/h" }));
        jPanel3.add(cb_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 150, 32));

        jLabel29.setText(" Año de fabricación");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 100, 10));
        jPanel3.add(caballero_fuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 100, 30));

        Reconstruido.setText("Reconstruido");
        jPanel3.add(Reconstruido, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 130, 30));
        jPanel3.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 120, 30));

        jTabbedPane3.addTab("Agregar Carro", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("Marca");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, 20));

        jLabel30.setText("Clasificación ");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, 20));

        jLabel31.setText("Precio");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, 20));

        ClasificacionPartes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spoiler", "Rear Bumper", "Front Bumper", "Side Skirts", "Front", "Fender", "Rear Fender", "Hood" }));
        jPanel5.add(ClasificacionPartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 180, -1));

        MarcaPartes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Advance", "DTM Fiberwerkz", "Fifteen52", "Origin Lab", "RocketBunny", "Urban Outlaw." }));
        jPanel5.add(MarcaPartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 77, 180, -1));
        jPanel5.add(PrecioPartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 180, 20));

        jButton6.setText("Crear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 260, 90));

        jTabbedPane3.addTab("Agregar Partes ", jPanel5);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 73, 110, -1));

        jLabel7.setText("Longitud");
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 75, -1, -1));

        jLabel15.setText("Cantidad de curvas ");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 112, -1, -1));

        jLabel16.setText(" Tipo de carreras");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 149, -1, -1));

        jLabel17.setText("Locacion");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 182, -1, -1));
        jPanel11.add(locacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 180, 110, -1));

        tipo_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drag", "Off-road ", "Circuito" }));
        tipo_carrera.setToolTipText("");
        jPanel11.add(tipo_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, -1));
        jPanel11.add(curvas, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 110, 110, -1));

        jButton9.setText("Crear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 190, 110));

        jTabbedPane3.addTab("Agregar Circuito", jPanel11);

        jButton3.setText("<-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuAdminLayout = new javax.swing.GroupLayout(MenuAdmin);
        MenuAdmin.setLayout(MenuAdminLayout);
        MenuAdminLayout.setHorizontalGroup(
            MenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
            .addGroup(MenuAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuAdminLayout.setVerticalGroup(
            MenuAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuAdminLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PantalladeCarga.setPreferredSize(new java.awt.Dimension(890, 610));
        PantalladeCarga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PantalladeCarga.add(barra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 620, 70));
        PantalladeCarga.add(barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 620, 70));

        iniciar_crear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Iniciar Sesion");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        Listo.setText("listo");
        Listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Listo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(i_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(i_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(Listo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Iniciar Sesion", jPanel2);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fecha de nacimiento:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 180, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Contraseña:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 20));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Correo:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, 20));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Pais de residencia:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 160, 20));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Registro");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, 30));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Usuario:");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 70, 20));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 262, 710, 10));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 70, 20));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel6.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 220, -1));

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        jPanel6.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 220, -1));

        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });
        jPanel6.add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 220, -1));

        Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisActionPerformed(evt);
            }
        });
        jPanel6.add(Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, -1));

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel6.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 220, -1));

        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Listo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 150, -1));
        jPanel6.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 210, -1));

        jTabbedPane1.addTab("Registro", jPanel6);

        iniciar_crear.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 890, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(iniciar_crear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PantalladeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(iniciar_crear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PantalladeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListoActionPerformed
        Hilopantalla hp;
        if (i_usuario.getText().equals("admin") && i_contrasena.getText().equals("admin")) {
            MenuAdmin.setVisible(true);
            iniciar_crear.setVisible(false);
        } else if (i_usuario.getText() != null && i_contrasena.getText() != null) {
            AdminJugador j = new AdminJugador("./Usuario.usr");
            j.cargarArchivo();
            boolean usuario_no_encontrado = true;
            int num1 = 0;
            int num2 = 0;
            for (jugador object : j.getLista()) {
                if (i_usuario.getText().equals(object.getUsuario()) && i_contrasena.getText().equals(object.getContraseña())) {
                    num1 = j.getLista().indexOf(object);
                    num2 = i_contrasena.getText().length();
                    usuario_no_encontrado = false;
                    usu.setText("" + i_usuario.getText());
                    usu.setVisible(false);
                    contra.setVisible(false);
                    contra.setText("" + i_contrasena.getText());
                }
            }
            num1++;
            hp = new Hilopantalla(PantalladeCarga, MenuUsuario, num1, num2, barra1, barra2);
            if (!usuario_no_encontrado) {
                iniciar_crear.setVisible(false);
                PantalladeCarga.setVisible(true);
                barra2.setVisible(false);
                hp.start();
            }
        }
        i_usuario.setText("");
        i_contrasena.setText("");
    }//GEN-LAST:event_ListoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContrasenaActionPerformed

    private void PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaisActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (nombre.getText() != null && Correo.getText() != null && Pais.getText() != null && Usuario.getText() != null && Contrasena.getText() != null) {
            boolean cumple_edad = validacion_fecha();
            if (cumple_edad) {
                boolean nombre_usuario = validacion_nombre_usuario_mismo_nombre();
                if (nombre_usuario) {
                    boolean contasena_no_valida = validando_nombre_contasena_2();
                    if (contasena_no_valida) {
                        AdminJugador j = new AdminJugador("./Usuario.usr");
                        j.cargarArchivo();
                        j.agregar(new jugador(fecha.getDate(), nombre.getText(), Correo.getText(), Pais.getText(), Usuario.getText(), Contrasena.getText()));
                        j.escribirArchivo();
                        nombre.setText("");
                        Correo.setText("");
                        Pais.setText("");
                        fecha.setDate(new Date());
                        Usuario.setText("");
                        Contrasena.setText("");

                        JOptionPane.showMessageDialog(this, "Se a registrado exitosamente");
                    } else {
                        JOptionPane.showMessageDialog(this, "Esta contraseña no es valida porque debe de:\nContener mínimo una letra mayúscula \nUna minúscula\nUn arácter especial");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Este nombre de usuario ya fue tomado");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Es menor de edad");
                nombre.setText("");
                Usuario.setText("");
                Contrasena.setText("");
                Correo.setText("");
                Pais.setText("");
                fecha.setDate(new Date());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void marca_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marca_cMouseClicked
        String marca = (String) marca_c.getSelectedItem();
        modelo_c.removeAllItems();

        switch (marca) {
            case "Subaru" -> {
                modelo_c.addItem("BRZ");
                modelo_c.addItem("Impreza");
                modelo_c.addItem("WPZ-X");
            }
            case "Toyota" -> {
                modelo_c.addItem("GT-86");
                modelo_c.addItem("Supra");
            }
            case "Honda" -> {
                modelo_c.addItem("Civic Type-R");
                modelo_c.addItem("Integra Type-K");
                modelo_c.addItem("CR-X");
            }
            case "Nissan" -> {
                modelo_c.addItem("Skyline-GTR34");
                modelo_c.addItem("Skyline-GTR32");
                modelo_c.addItem("GTR-R35");
            }
            case "Ferrari" -> {
                modelo_c.addItem("LaFerrari");
                modelo_c.addItem("Testorroso");
                modelo_c.addItem("240");

            }
            case "Lamborghini" -> {
                modelo_c.addItem("Diablo");
                modelo_c.addItem("Huracan");
                modelo_c.addItem("Murcielago");
            }
            case "Ford" -> {
                modelo_c.addItem("Mustang");
                modelo_c.addItem("F-150");
            }
            case "Chevrolet" -> {
                modelo_c.addItem("Camaro");
                modelo_c.addItem("Bel-Hir");
            }

            case "Acorh" -> {
                modelo_c.addItem("NSX");
            }
            case "BWW" -> {
                modelo_c.addItem("M3");
                modelo_c.addItem("X6");
                modelo_c.addItem("M5");
            }
            case "Mercedes-Benz" -> {
                modelo_c.addItem("Clase A");
                modelo_c.addItem("GLA");
                modelo_c.addItem("GLC");
                modelo_c.addItem("GLS");
            }

            case "VW" -> {
                modelo_c.addItem("Beetle");
            }
            case "Audi" -> {
                modelo_c.addItem("RB");
                modelo_c.addItem("T-Coupe");
            }
            case "Porsche" -> {
                modelo_c.addItem("All Carrera");
                modelo_c.addItem("978");
            }
            default ->
                throw new AssertionError();
        }
    }//GEN-LAST:event_marca_cMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        Color color = JColorChooser.showDialog(this, "Color del carro", Color.yellow);
        carro_color.setBackground(color);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void pais_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pais_cMouseClicked
        String pais = (String) pais_c.getSelectedItem();
        marca_c.removeAllItems();

        switch (pais) {
            case "Japon":
                marca_c.addItem("Subaru");
                marca_c.addItem("Toyota");
                marca_c.addItem("Honda");
                marca_c.addItem("Mitsubishi");
                marca_c.addItem("Nissan");
                break;
            case "Italia":
                marca_c.addItem("Ferrari");
                marca_c.addItem("Lamborghini");
                break;
            case "USA":
                marca_c.addItem("Ford");
                marca_c.addItem("Chevrolet");
                marca_c.addItem("Acorh");
                break;
            case "Alemania":
                marca_c.addItem("BWW");
                marca_c.addItem("Mercedes-Benz");
                marca_c.addItem("VW");
                marca_c.addItem("Audi");
                marca_c.addItem("Porsche");
                break;
            default:
                System.out.println("Valor inesperado de país: " + pais);

                throw new AssertionError();
        }
    }//GEN-LAST:event_pais_cMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String marca = "" + pais_c.getSelectedItem();
        String modelo = "" + marca_c.getSelectedItem();
        String pais = "" + modelo_c.getSelectedItem();
        Color color = carro_color.getBackground();
        double precio = Double.parseDouble(precio_carro.getText());
        Date fecha = Fecha.getDate();
        int Horsepower = Integer.parseInt(caballero_fuerza.getText());
        int VelocidadP = Integer.parseInt(velocidad_punta.getText());
        boolean reconstruido = Reconstruido.isSelected();
        int tiempo = 0;
        if (cb_tiempo.getSelectedIndex() == 0) {
            tiempo = 60;
        } else if (cb_tiempo.getSelectedIndex() == 1) {
            tiempo = 100;
        }
        AdminCarro AC = new AdminCarro("./Carros.car");
        AC.cargarArchivo();
        carro temp = new carro(marca, modelo, color, precio, pais, fecha, reconstruido, Horsepower, VelocidadP, tiempo);
        AC.agregar(temp);
        AC.escribirArchivo();
        AdminConcesionaria AdC = new AdminConcesionaria("./Consesionaria.cns");
        AdC.cargarArchivo();
        ArrayList<concesionaria> con = AdC.getLista();
        con.get(cb_concesionaria.getSelectedIndex()).getC().add(temp);
        AdC.setlista(con);
        AdC.escribirArchivo();
        precio_carro.setText("");
        caballero_fuerza.setText("");
        velocidad_punta.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTabbedPane3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane3StateChanged
        if (jTabbedPane3.getSelectedIndex() == 1) {
            AdminConcesionaria AdC = new AdminConcesionaria("./Consesionaria.cns");
            AdC.cargarArchivo();
            ArrayList<concesionaria> c = AdC.getLista();
            cb_concesionaria.removeAllItems();
            for (concesionaria object : c) {
                cb_concesionaria.addItem("" + object);
            }
        }
    }//GEN-LAST:event_jTabbedPane3StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdminConcesionaria AdC = new AdminConcesionaria("./Consesionaria.cns");
        AdC.cargarArchivo();
        ArrayList<concesionaria> c = AdC.getLista();
        c.add(new concesionaria(ConcesionariaNombre.getText(), ConcesionariaLocacion.getText()));
        AdC.escribirArchivo();
        ConcesionariaNombre.setText("");
        ConcesionariaLocacion.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AdminPartes AdPartes = new AdminPartes("./Partes.pt");
        String marca = "" + MarcaPartes.getSelectedItem();
        String clasificacion = "" + ClasificacionPartes.getSelectedItem();
        double precio = Double.parseDouble(PrecioPartes.getText());
        AdPartes.cargarArchivo();
        AdPartes.agregar(new partes(marca, clasificacion, precio));
        AdPartes.escribirArchivo();
        PrecioPartes.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        AdminCircuito AdCir = new AdminCircuito("./Circuitos.cct");
        AdCir.cargarArchivo();
        int Longi = Integer.parseInt(longitud.getText());
        int Cantidad = Integer.parseInt(curvas.getText());
        String tipo = "" + tipo_carrera.getSelectedItem();
        String loc = "" + locacion.getText();
        AdCir.agregar(new circuito(Longi, Cantidad, tipo, loc));
        AdCir.escribirArchivo();
        longitud.setText("");
        curvas.setText("");
        locacion.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        iniciar_crear.setVisible(true);
        MenuAdmin.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        iniciar_crear.setVisible(true);
        MenuUsuario.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        HiloGaraje hg = new HiloGaraje(tablacompra, usu.getText(), contra.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        HiloGaraje hg = new HiloGaraje(tablacompra, usu.getText(), contra.getText());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    public boolean validacion_nombre_usuario_mismo_nombre() {
        AdminJugador j = new AdminJugador("./Usuario.usr");
        for (jugador object : j.getLista()) {
            if (object.getUsuario().equals(Usuario.getText())) {
                return false;
            }
        }
        return true;
    }

    public boolean validando_nombre_contasena_2() {
        String c = Contrasena.getText();
        int mayuscula = 0;
        int minuscula = 0;
        int especial = 0;
        for (int i = 0; i < c.length(); i++) {
            char letra = c.charAt(i);
            if ((int) letra >= 97 && (int) letra <= 122) {
                minuscula++;
            }
            if ((int) letra >= 65 && (int) letra <= 90) {
                mayuscula++;
            }
            if ((int) letra >= 33 && (int) letra <= 47) {
                especial++;
            }
            if ((int) letra >= 58 && (int) letra <= 64) {
                especial++;
            }
        }
        if (mayuscula == 0 || minuscula == 0 || especial == 0) {
            return false;
        } else {
            return true;
        }
    }

    public boolean validacion_fecha() {
        Date nacimiento = fecha.getDate();
        int year = nacimiento.getYear() + 1900, dia = nacimiento.getDay(), mes = nacimiento.getMonth() + 1;
        Date hoy = new Date();
        int year1 = hoy.getYear() + 1900, dia1 = hoy.getDay(), mes1 = hoy.getMonth() + 1, diferencia = 0;
        diferencia = year1 - year;
        if (mes1 >= mes) {
            if (dia1 >= dia && mes1 == mes) {
            } else if (mes1 == mes) {
                diferencia--;
            }
        } else {
            diferencia--;
        }
        if (diferencia <= 12) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClasificacionPartes;
    private javax.swing.JTextField ConcesionariaLocacion;
    private javax.swing.JTextField ConcesionariaNombre;
    private javax.swing.JTextField Contrasena;
    private javax.swing.JTextField Correo;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JButton Listo;
    private javax.swing.JComboBox<String> MarcaPartes;
    private javax.swing.JPanel MenuAdmin;
    private javax.swing.JPanel MenuUsuario;
    private javax.swing.JTextField Pais;
    private javax.swing.JPanel PantalladeCarga;
    private javax.swing.JTextField PrecioPartes;
    private javax.swing.JCheckBox Reconstruido;
    private javax.swing.JTextField Usuario;
    private javax.swing.JProgressBar barra1;
    private javax.swing.JProgressBar barra2;
    private javax.swing.JTextField caballero_fuerza;
    private javax.swing.JPanel carro_color;
    private javax.swing.JComboBox<String> cb_concesionaria;
    private javax.swing.JComboBox<String> cb_tiempo;
    private javax.swing.JLabel contra;
    private javax.swing.JTextField curvas;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JTextField i_contrasena;
    private javax.swing.JTextField i_usuario;
    private javax.swing.JPanel iniciar_crear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField locacion;
    private javax.swing.JTextField longitud;
    private javax.swing.JComboBox<String> marca_c;
    private javax.swing.JComboBox<String> modelo_c;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> pais_c;
    private javax.swing.JTextField precio_carro;
    private javax.swing.JTable tablacompra;
    private javax.swing.JComboBox<String> tipo_carrera;
    private javax.swing.JLabel usu;
    private javax.swing.JTextField velocidad_punta;
    // End of variables declaration//GEN-END:variables
}
